# mysql
mysql:
  username: "root"
  password: "20010428"
  host: "127.0.0.1"
  port: 3306
  database: "antd-admin"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"

# Redis 配置
redis:
  host: "127.0.0.1:6379" # Redis 服务器主机地址
  password: "" # Redis 访问密码（如果有的话）
  db: 0 # Redis 数据库编号（默认为 0）
  poolSize: 30
  minIdleConn: 30

# Log
Log:
  LogFilePath: /usr/share/nginx/html/config/logs
  LogInfoFileName: info
  LogWarnFileName: warn
  LogFileExt: log
  RunMode: debug

AccessLog:
  LogFilePath: /usr/share/nginx/html/config/logs
  LogFileName: router_info
  LogFileExt: log
